language: r
cache: packages
pandoc_version: 2.9.2.1

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - csgillespie/efficient

script:
  - R CMD INSTALL ../efficientR/
  - make html

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
